# -*- coding: utf-8 -*-
"""
Data processing for mechanical characterization tests (e.g., tension, compression, 3 pts bending).
Files are expected to be in a text-like format (.txt, .dat) with the following
tab-separated columns:
    t (time [s]) \t F (force [N]) \t u (displacement [mm])

This script is part of an endeavour to standardize the data
 processing of constitutive and resistance material properties
  for mechanical testing of engeneering materials.

2015 -- 2025

by Goryunov @2025
"""

## Required libraries
import numpy as np
import matplotlib.pyplot as plt
from cycler import cycler
import pandas as pd
import os
import statistics as st

#
# -- VISUAL IDENTITY SETUP (Politecnico di Torino) --
#
# Define core colors from the brand identity
POLITO_BLUE = '#002B49'
POLITO_ORANGE = '#EF7B00'
POLITO_BLACK = '#000000'

# Secondary colors (page 28 of the visual identity manual)
POLITO_GREEN = '#50A060'
POLITO_LIGHT_BLUE = '#4090C0'
POLITO_PURPLE = '#804080'
POLITO_RED = '#D04040'


# Update Matplotlib's runtime configuration parameters (rcParams)
# This will apply the style to ALL plots generated by the script.
# NOTE: The 'Poppins' font must be installed on your system.
try:
    plt.rcParams.update({
        'font.family': 'Poppins',
        'font.size': 12,
        'text.color': POLITO_BLACK,
        'axes.labelcolor': POLITO_BLACK,
        'axes.titlecolor': POLITO_BLACK,
        'xtick.color': POLITO_BLACK,
        'ytick.color': POLITO_BLACK,
        'axes.edgecolor': POLITO_BLACK,
        'grid.color': 'lightgray',
        'grid.linestyle': '--',
        # Expansion of the colors cycle
        'axes.prop_cycle': cycler('color', [
            POLITO_BLUE, 
            POLITO_ORANGE, 
            POLITO_GREEN, 
            POLITO_LIGHT_BLUE, 
            POLITO_RED, 
            POLITO_PURPLE, 
            '#5A5A5A', 
            '#A8A8A8'
        ]),
        'axes.titlesize': 'large',
        'axes.labelsize': 'medium',
        'legend.fontsize': 'small'
    })
except Exception as e:
    print(f"Warning: Could not set font to 'Poppins'. Make sure it is installed. Falling back to default. Error: {e}")
#
## ------------ THIS ENTRIES MUST BE UPDATED ------------
#
# Specimen geometry and test parameters
L0 = 150e-3 # Gauge length for strain calculation [m]
A = 100e-6 # Cross-section area [m^2]
#
# Labels for plots
tlbl = 'Time $[\\text{s}]$'
flbl = 'Force $[\\text{N}]$'
ulbl = 'Displacement $[\\text{mm}]$'
stresslbl = 'Stress ($\\sigma$) $[\\text{MPa}]$'
strainlbl = 'Strain ($\\epsilon$) $[\\text{mm/mm}]$'
#
# Strain region to compute the elastic modulus (linear fit)
lin_inf = 0.0005 # Lower strain limit [mm/mm] (e.g., 0.05%)
lin_sup = 0.01 # Upper strain limit [mm/mm] (e.g., 1.0%)
#
# Choose if figures will be saved ('Y') or not ('N')
save_fig = 'N' # To test the script, it is advised to turn it off
# Define the standard output file format to save figures
stdformat = 'svg' # 'pdf' # 'png'
#
## ------------ USEFUL FUNCTIONS ------------
#
def plot_raw(t, u, F, specimen_id):
    """Plots raw data: Force vs. Time and Force vs. Displacement."""
    fig, axs = plt.subplots(2, 1, figsize=(8, 6))
    fig.suptitle(f'Raw Data: Sample {specimen_id}', fontsize=16)

    # Force vs. Time
    axs[0].plot(t, F, color=POLITO_BLUE, linestyle='-', label=f'Sample: {specimen_id}')
    axs[0].legend(loc='lower right')
    axs[0].set_xlabel(tlbl)
    axs[0].set_ylabel(flbl)
    axs[0].grid(True)

    # Force vs. Displacement
    axs[1].plot(u, F, color=POLITO_BLUE, linestyle='-', label=f'Sample: {specimen_id}')
    axs[1].legend(loc='lower right')
    axs[1].set_xlabel(ulbl)
    axs[1].set_ylabel(flbl)
    axs[1].grid(True)

    fig.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()
    
    if save_fig == 'Y':
        img_name = f'Raw_data_{specimen_id}.{stdformat}'
        fig.savefig(img_name, format=stdformat, dpi=600, bbox_inches='tight')

def plot_stress_strain(strain, stress, specimen_id):
    """Plots the Stress vs. Strain curve."""
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(strain, stress, color=POLITO_BLUE, linestyle='-', linewidth=2, label=f'Sample: {specimen_id}')
    ax.legend(loc='lower right')
    ax.set_title(f'Stress vs. Strain Curve: {specimen_id}')
    ax.set_xlabel(strainlbl)
    ax.set_ylabel(stresslbl)
    ax.grid(True)
    plt.show()

    if save_fig == 'Y':
        img_name = f'Stress_vs_Strain_{specimen_id}.{stdformat}'
        fig.savefig(img_name, format=stdformat, dpi=600, bbox_inches='tight')

def plot_linear_fit(strain, stress, specimen_id):
    """Calculates Elastic Modulus from a linear fit and plots it."""
    fig, ax = plt.subplots(figsize=(8, 5))
    
    ax.plot(strain, stress, linestyle='dotted', linewidth=1.5, color='gray', label='Complete Data')
    
    fit_indices = np.where((strain >= lin_inf) & (strain <= lin_sup))
    strain_fit = strain[fit_indices]
    stress_fit = stress[fit_indices]

    if len(strain_fit) < 2:
        print(f"WARNING: Not enough data in linear range for sample {specimen_id}. Modulus not computed.")
        ax.text(0.5, 0.5, 'Modulus Not Computed', horizontalalignment='center', verticalalignment='center', transform=ax.transAxes)
        plt.show()
        return np.nan

    m, b = np.polyfit(strain_fit, stress_fit, 1)
    
    y_pred = m * strain_fit + b
    ss_res = np.sum((stress_fit - y_pred) ** 2)
    ss_tot = np.sum((stress_fit - np.mean(stress_fit)) ** 2)
    r2 = 1 - (ss_res / ss_tot)

    line_strain = np.array([0, lin_sup * 1.2]) 
    line_stress = m * line_strain + b

    ax.plot(strain_fit, stress_fit, 'o', color=POLITO_BLUE, label='Data for Fitting')
    ax.plot(line_strain, line_stress, '-', color=POLITO_ORANGE, linewidth=2.5, label=f'Linear Fit (E = {m:.2f} MPa)')
    
    ax.set_ylabel(stresslbl)
    ax.set_xlabel(strainlbl)
    ax.legend(loc='lower right')
    ax.set_title(f'Elastic Modulus Fitting: {specimen_id}')
    ax.grid(True)

    text_str = f'$E = {m:.2f}$ MPa\n$R^2 = {r2:.4f}$'
    ax.text(0.05, 0.95, text_str, transform=ax.transAxes, fontsize=12,
            verticalalignment='top', bbox=dict(boxstyle='round', facecolor=POLITO_ORANGE, alpha=0.1))
    
    plt.show()
    
    if save_fig == 'Y':
        img_name = f'LinearFit_{specimen_id}.{stdformat}'
        fig.savefig(img_name, format=stdformat, dpi=600, bbox_inches='tight')
        
    return m

def plot_summary_bar(results, labels):
    """Plots a bar chart summarizing a given property."""
    if not results:
        return

    avg_val = st.mean(results)
    std_dev = st.stdev(results) if len(results) > 1 else 0

    fig, ax = plt.subplots(figsize=(8, 6))
    
    x_pos = np.arange(len(labels))
    ax.bar(x_pos, results, color=POLITO_BLUE, yerr=std_dev, align='center', alpha=0.9, ecolor=POLITO_BLACK, capsize=5)
    
    ax.axhline(y=avg_val, color=POLITO_ORANGE, linestyle='--', linewidth=2, label=f'Average = {avg_val:.2f} MPa')
    
    ax.set_ylabel('Elastic Modulus (E) [MPa]')
    ax.set_xlabel('Sample')
    ax.set_xticks(x_pos)
    ax.set_xticklabels(labels, rotation=45, ha='right')
    ax.set_title(f'Summary of Elastic Moduli\n(Standard Deviation = {std_dev:.2f} MPa)')
    ax.yaxis.grid(True)
    ax.legend()
    
    plt.tight_layout()
    plt.show()
    
    if save_fig == 'Y':
        img_name = f'BarPlot_Summary.{stdformat}'
        fig.savefig(img_name, format=stdformat, dpi=600, bbox_inches='tight')

#
## ------------ SCRIPT MAIN LOGIC STARTS HERE ------------
#
path = os.path.abspath(os.getcwd())
all_files = [f for f in os.listdir(path) if f.endswith(".txt")]

all_data = []
elastic_moduli = []
specimen_ids = []

for filename in all_files:
    specimen_id = os.path.splitext(filename)[0]
    specimen_ids.append(specimen_id)
    print(f"--- Processing file: {filename} ---")
    
    file_path = os.path.join(path, filename)
    raw_data = np.genfromtxt(file_path, comments='#', delimiter='\t')
    all_data.append(raw_data)
    
    t = raw_data[:, 0]
    F = raw_data[:, 1]
    u = raw_data[:, 2]
    
    strain = (u * 1e-3) / L0
    stress = (F / A) * 1e-6
    
    plot_raw(t, u, F, specimen_id)
    plot_stress_strain(strain, stress, specimen_id)
    modulus = plot_linear_fit(strain, stress, specimen_id)
    
    if not np.isnan(modulus):
        elastic_moduli.append(modulus)

if elastic_moduli:
    print("\n--- Statistical Summary (Elastic Modulus) ---")
    print(f"Values (MPa): {[f'{val:.2f}' for val in elastic_moduli]}")
    print(f"Average: {st.mean(elastic_moduli):.2f} MPa")
    if len(elastic_moduli) > 1:
        print(f"Standard Deviation: {st.stdev(elastic_moduli):.2f} MPa")
    
    plot_summary_bar(elastic_moduli, specimen_ids)

# Plot all Force vs. Displacement curves overlapped
fig, ax = plt.subplots(figsize=(8, 6))
for i, data in enumerate(all_data):
    u = data[:, 2]
    F = data[:, 1]
    ax.plot(u, F, label=specimen_ids[i], linewidth=2)

ax.set_xlabel(ulbl)
ax.set_ylabel(flbl)
ax.set_title('Overlapped Curves: Force vs. Displacement')
ax.legend(loc='best')
ax.grid(True)
fig.tight_layout()
plt.show()

if save_fig == 'Y':
    img_name = f'All_Curves_Overlapped.{stdformat}'
    fig.savefig(img_name, format=stdformat, dpi=600, bbox_inches='tight')

print("\nData processing finished.")